<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Module.Identity</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <SharedReference Include="Contracts" />
    <SharedReference Include="Data" />
    <SharedReference Include="Kernel" />
    <SharedReference Include="Http" />
    <SharedReference Include="Observability" />
    <SharedReference Include="Messaging" />
    <SharedReference Include="WebHost" />
    <ProjectReference Include="../../shared/Shared.Contracts.Modules/Shared.Contracts.Modules.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Tests.Unit" />
  </ItemGroup>
</Project>
