<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Shared.Http</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Tests.Unit" />
    <InternalsVisibleTo Include="Tests.Architecture" />
    <InternalsVisibleTo Include="Tests.Integration" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <ProjectReference Include="../Shared.Observability/Shared.Observability.csproj" />
    <ProjectReference Include="../Shared.Data/Shared.Data.csproj" />
  </ItemGroup>
</Project>
