<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Module.Venues</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Tests.Unit" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <SharedReference Include="Shared.Contracts" />
    <SharedReference Include="Shared.Data" />
    <SharedReference Include="Shared.Kernel" />
    <SharedReference Include="Shared.Http" />
    <SharedReference Include="Shared.Observability" />
    <SharedReference Include="Shared.Messaging" />
    <SharedReference Include="Shared.WebHost" />
    <ProjectReference Include="../../shared/Shared.Contracts.Modules/Shared.Contracts.Modules.csproj" />
  </ItemGroup>
</Project>
